#!/usr/bin/env python3
"""Generate a Claude Code status line script from a choice.json layout.

Usage: python3 generate.py <choice.json> <output-script.py>
The output is a self-contained python3 status line script with the chosen
layout baked in, handling every supported segment with null-safe extraction.
"""
import sys
import json

TEMPLATE = r'''#!/usr/bin/env python3
# Generated by the status line designer. Reads Claude Code session JSON on stdin.
import sys, os, json, time, getpass, socket, subprocess

CONFIG = json.loads(__CONFIGREPR__)

EMOJI = {"cwd":"\U0001F4C1","cost":"\U0001F4B0","duration":"⏱️","gitbranch":"\U0001F33F",
         "projectdir":"\U0001F4C2","repo":"\U0001F517","thinking":"\U0001F9E0","pr":"⇡","fastmode":"⚡"}
PLAIN = {"colon"}
GRAD = {"ctxpct", "lim5h", "lim7d"}  # bars colored green(ample)->red(critical) by usage

# Soft palette matching the web designer exactly (Tokyo Night), emitted as truecolor
# so terminal colors are identical to the web preview (not the terminal's ANSI theme).
COLORS_HEX = {
    "default": "c0caf5", "gray": "7a83a6", "white": "ffffff",
    "red": "f7768e", "green": "9ece6a", "yellow": "e0af68", "blue": "7aa2f7",
    "magenta": "bb9af7", "cyan": "7dcfff", "brightred": "ff7a93", "brightgreen": "b9f27c",
    "brightyellow": "ffd479", "brightblue": "9db8ff", "brightmagenta": "d2a8ff", "brightcyan": "a4e8ff",
}

def hex_rgb(h):
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def desat(r, g, b, k=0.4):
    # mix each channel toward the colour's own luma -> lower saturation, same brightness
    y = 0.3 * r + 0.59 * g + 0.11 * b
    return round(r + (y - r) * k), round(g + (y - g) * k), round(b + (y - b) * k)

def hsl_rgb(h, s, l):
    c = (1 - abs(2 * l - 1)) * s
    x = c * (1 - abs((h / 60.0) % 2 - 1))
    m = l - c / 2
    if h < 60:    r, gg, b = c, x, 0
    elif h < 120: r, gg, b = x, c, 0
    elif h < 180: r, gg, b = 0, c, x
    elif h < 240: r, gg, b = 0, x, c
    elif h < 300: r, gg, b = x, 0, c
    else:         r, gg, b = c, 0, x
    return int(round((r + m) * 255)), int(round((gg + m) * 255)), int(round((b + m) * 255))

def grad_rgb(pct):
    pct = max(0.0, min(100.0, float(pct)))
    return hsl_rgb(120 * (1 - pct / 100.0), 0.45, 0.55)

def g(d, *path, default=None):
    cur = d
    for p in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(p)
        if cur is None:
            return default
    return cur

def kfmt(n):
    try:
        n = float(n)
    except (TypeError, ValueError):
        return "?"
    if n >= 1000000:
        return ("%.1fM" % (n / 1000000)).replace(".0M", "M")
    if n >= 1000:
        return "%dk" % round(n / 1000)
    return str(int(n))

def dur(ms):
    s = int(ms) // 1000
    if s >= 3600:
        return "%dh %dm" % (s // 3600, (s % 3600) // 60)
    return "%dm %ds" % (s // 60, s % 60)

def countdown(resets_at):
    diff = int(resets_at) - int(time.time())
    if diff <= 0:
        return "now"
    d, h, m = diff // 86400, (diff % 86400) // 3600, (diff % 3600) // 60
    if d:
        return "%dd%dh" % (d, h)
    if h:
        return "%dh%dm" % (h, m)
    return "%dm" % m

def pretty_model(mid):
    if not mid:
        return None
    parts = [p for p in mid.split("-") if p != "claude"]
    fam, ver = [], []
    for p in parts:
        if p.isdigit():
            if len(p) >= 6:      # skip date stamps like 20251001
                continue
            ver.append(p)
        else:
            fam.append(p.capitalize())
    name = " ".join(fam)
    if ver:
        name += " " + ".".join(ver)
    return name.strip() or mid

_git = None
def git_info(d):
    global _git
    if _git is not None:
        return _git
    sid = g(d, "session_id", default="x")
    cache = "/tmp/statusline-git-%s" % sid
    try:
        fresh = os.path.exists(cache) and (time.time() - os.path.getmtime(cache) <= 5)
    except OSError:
        fresh = False
    if not fresh:
        try:
            subprocess.check_output(["git", "rev-parse", "--git-dir"], stderr=subprocess.DEVNULL)
            br = subprocess.check_output(["git", "branch", "--show-current"], text=True, stderr=subprocess.DEVNULL).strip()
            st = subprocess.check_output(["git", "diff", "--cached", "--numstat"], text=True, stderr=subprocess.DEVNULL).strip()
            md = subprocess.check_output(["git", "diff", "--numstat"], text=True, stderr=subprocess.DEVNULL).strip()
            s = len(st.splitlines()) if st else 0
            m = len(md.splitlines()) if md else 0
            open(cache, "w").write("%s\t%d\t%d" % (br, s, m))
        except Exception:
            open(cache, "w").write("\t0\t0")
    try:
        br, s, m = open(cache).read().split("\t")
        _git = (br, int(s), int(m))
    except Exception:
        _git = ("", 0, 0)
    return _git

_totals = None
def session_totals(d):
    """Cumulative session token usage, summed from each API call in the transcript.
    The transcript logs each assistant message multiple times (streaming), all copies
    carrying identical usage — so we DEDUPE by message.id (each id = one billed call).
    Parsed incrementally (only new bytes since last run); offset, running totals, and
    the set of counted message ids are cached on disk."""
    global _totals
    if _totals is not None:
        return _totals
    path = g(d, "transcript_path")
    if not path or not os.path.exists(path):
        _totals = {}
        return _totals
    cache = "/tmp/statusline-tokens3-%s" % g(d, "session_id", default="x")
    off = ti = to = cr = c5 = c1 = 0
    seen = set()
    try:
        c = json.loads(open(cache).read())
        off, ti, to, cr, c5, c1 = c["off"], c["ti"], c["to"], c["cr"], c["c5"], c["c1"]
        seen = set(c["ids"])
    except Exception:
        off = ti = to = cr = c5 = c1 = 0; seen = set()   # missing/old-schema cache -> full reparse
    try:
        if off > os.path.getsize(path):     # transcript shrank (compact/rewrite) -> reparse
            off = ti = to = cr = c5 = c1 = 0; seen = set()
        with open(path, "rb") as f:
            f.seek(off)
            data = f.read()
        consumed = 0
        for line in data.splitlines(keepends=True):
            if not line.endswith(b"\n"):     # don't count a half-written trailing line
                break
            consumed += len(line)
            try:
                m = json.loads(line).get("message")
                u = m.get("usage") if isinstance(m, dict) else None
                mid = m.get("id") if isinstance(m, dict) else None
            except Exception:
                u = mid = None
            if isinstance(u, dict) and mid and mid not in seen:   # one count per API call
                seen.add(mid)
                ti += u.get("input_tokens") or 0
                to += u.get("output_tokens") or 0
                cr += u.get("cache_read_input_tokens") or 0
                cc = u.get("cache_creation")
                if isinstance(cc, dict):
                    c5 += cc.get("ephemeral_5m_input_tokens") or 0   # 5-minute cache writes
                    c1 += cc.get("ephemeral_1h_input_tokens") or 0   # 1-hour cache writes
        off += consumed
        try:
            open(cache, "w").write(json.dumps(
                {"off": off, "ti": ti, "to": to, "cr": cr, "c5": c5, "c1": c1, "ids": list(seen)}))
        except Exception:
            pass
    except Exception:
        pass
    _totals = {"input": ti, "output": to, "cache_read": cr,
               "cache_5m": c5, "cache_1h": c1, "cache_write": c5 + c1}
    return _totals

def render(seg, d):
    i = seg["id"]
    if i == "userhost":
        return "%s@%s" % (getpass.getuser(), socket.gethostname().split(".")[0])
    if i == "colon":
        return ":"
    if i == "cwd":
        cwd = g(d, "cwd") or g(d, "workspace", "current_dir") or os.getcwd()
        mode = seg.get("mode") or "~"
        if mode == "basename":
            return os.path.basename(cwd.rstrip("/")) or cwd
        if mode == "full":
            return cwd
        home = os.path.expanduser("~")
        if cwd == home:
            return "~"
        if cwd.startswith(home + "/"):
            return "~" + cwd[len(home):]
        return cwd
    if i == "model":
        mode = seg.get("mode") or "version"
        if mode == "name":
            return g(d, "model", "display_name")
        if mode == "id":
            return g(d, "model", "id")
        return pretty_model(g(d, "model", "id")) or g(d, "model", "display_name")
    if i == "ctxpct":
        p = g(d, "context_window", "used_percentage")
        if p is None:
            return None
        p = int(float(p))
        if seg.get("bar"):
            f = max(0, min(10, round(p / 10)))
            return "%s %d%%" % ("█" * f + "░" * (10 - f), p)
        return "%d%% ctx" % p
    if i == "ctxremain":
        r = g(d, "context_window", "remaining_percentage")
        return None if r is None else "%d%% left" % int(float(r))
    if i == "ctxtokens":
        ti = g(d, "context_window", "total_input_tokens")
        sz = g(d, "context_window", "context_window_size")
        return None if ti is None else "%s/%s" % (kfmt(ti), kfmt(sz))
    if i in ("lim5h", "lim7d"):
        win = "five_hour" if i == "lim5h" else "seven_day"
        label = "5h" if i == "lim5h" else "7d"
        p = g(d, "rate_limits", win, "used_percentage")
        if p is None:
            return None
        p = float(p)
        t = label + " "
        if seg.get("bar"):
            f = max(0, min(10, round(p / 10)))
            t += "█" * f + "░" * (10 - f) + " "
        t += "%d%%" % round(p)
        ra = g(d, "rate_limits", win, "resets_at")
        if seg.get("reset") and ra:
            t += " (%s)" % countdown(ra)
        return t
    if i == "cost":
        c = g(d, "cost", "total_cost_usd")
        return None if c is None else "$%.2f" % float(c)
    if i == "duration":
        ms = g(d, "cost", "total_duration_ms")
        return None if ms is None else dur(ms)
    if i == "lines":
        a = g(d, "cost", "total_lines_added", default=0)
        r = g(d, "cost", "total_lines_removed", default=0)
        return "+%d -%d" % (int(a), int(r))
    if i == "gitbranch":
        br = git_info(d)[0]
        return br or None
    if i == "gitstatus":
        br, s, m = git_info(d)
        if not br:
            return None
        return "+%d ~%d" % (s, m)
    if i == "style":
        return g(d, "output_style", "name")
    if i == "projectdir":
        pd = g(d, "workspace", "project_dir")
        return os.path.basename(pd.rstrip("/")) if pd else None
    if i == "addeddirs":
        arr = g(d, "workspace", "added_dirs", default=[])
        if not isinstance(arr, list):
            return None
        cwd = g(d, "cwd") or g(d, "workspace", "current_dir")
        proj = g(d, "workspace", "project_dir")
        extra = [x for x in arr if x not in (cwd, proj)]  # only dirs added beyond the workspace
        if not extra:
            return None
        if len(extra) == 1:
            return os.path.basename(extra[0].rstrip("/")) or "+1 dir"  # name it, so it's not a mystery
        return "+%d dirs" % len(extra)
    if i == "repo":
        owner = g(d, "workspace", "repo", "owner")
        name = g(d, "workspace", "repo", "name")
        if not name:
            return None
        return "%s/%s" % (owner, name) if owner else name
    if i == "worktree":
        return g(d, "worktree", "name") or g(d, "worktree", "branch") or g(d, "workspace", "git_worktree")
    if i == "apidur":
        ms = g(d, "cost", "total_api_duration_ms")
        return None if ms is None else "api %.1fs" % (float(ms) / 1000)
    if i == "cachetok":
        tot = session_totals(d)
        if tot:   # cache 5m-writes / 1h-writes / hits&refreshes (Claude API billing items)
            return "cache %s/%s/%s" % (kfmt(tot.get("cache_5m", 0)), kfmt(tot.get("cache_1h", 0)), kfmt(tot.get("cache_read", 0)))
        cr = g(d, "context_window", "current_usage", "cache_read_input_tokens")
        cc = g(d, "context_window", "current_usage", "cache_creation_input_tokens")
        if cr is None and cc is None:
            return None
        return "cache %s/%s" % (kfmt(cr or 0), kfmt(cc or 0))
    if i == "tokin":
        t = session_totals(d).get("input")
        if t is None:
            t = g(d, "context_window", "total_input_tokens")
        return None if t is None else "in %s" % kfmt(t)
    if i == "tokout":
        t = session_totals(d).get("output")
        if t is None:
            t = g(d, "context_window", "total_output_tokens")
        return None if t is None else "out %s" % kfmt(t)
    if i == "exceeds":
        return "⚠ 200k+" if g(d, "exceeds_200k_tokens") else None
    if i == "effort":
        return g(d, "effort", "level")
    if i == "thinking":
        t = g(d, "thinking", "enabled")
        return None if t is None else ("on" if t else "off")
    if i == "fastmode":
        return "fast" if g(d, "fast_mode") else None
    if i == "vim":
        return g(d, "vim", "mode")
    if i == "agent":
        return g(d, "agent", "name")
    if i == "pr":
        n = g(d, "pr", "number")
        if n is None:
            return None
        t = "PR #%s" % n
        rs = g(d, "pr", "review_state")
        return t + (" (%s)" % rs if rs else "")
    if i == "sesname":
        return g(d, "session_name")
    if i == "sesid":
        sid = g(d, "session_id")
        return sid[:8] if sid else None
    if i == "version":
        v = g(d, "version")
        return "v%s" % v if v else None
    return None

def link_url(seg, d):
    if seg["id"] == "repo":
        host = g(d, "workspace", "repo", "host")
        owner = g(d, "workspace", "repo", "owner")
        name = g(d, "workspace", "repo", "name")
        if host and owner and name:
            return "https://%s/%s/%s" % (host, owner, name)
    if seg["id"] == "pr":
        return g(d, "pr", "url")
    return None

def usage_pct(i, d):
    if i == "ctxpct":
        return g(d, "context_window", "used_percentage")
    if i == "lim5h":
        return g(d, "rate_limits", "five_hour", "used_percentage")
    if i == "lim7d":
        return g(d, "rate_limits", "seven_day", "used_percentage")
    return None

def color_seq(seg, d):
    """SGR color parameters (no leading ESC[ / trailing m). Gradient for usage bars."""
    i = seg["id"]
    if i in GRAD:
        p = usage_pct(i, d)
        if p is not None:
            r, gg, b = grad_rgb(p)
            return "38;2;%d;%d;%d" % (r, gg, b)
    h = COLORS_HEX.get(seg.get("color", "default"))
    if h:
        r, gg, b = desat(*hex_rgb(h))
        return "38;2;%d;%d;%d" % (r, gg, b)
    return "%d" % seg.get("colorCode", 39)

def main():
    try:
        d = json.loads(sys.stdin.read())
    except Exception:
        d = {}
    emoji_on = CONFIG.get("emoji", True)
    sep = CONFIG.get("separator", " ")
    lines = {1: [], 2: []}
    for seg in CONFIG["segments"]:
        try:
            txt = render(seg, d)
        except Exception:
            txt = None
        if not txt:
            continue
        lines.setdefault(seg.get("line", 1), []).append((seg, txt))
    out = []
    for ln in (1, 2):
        parts = lines.get(ln, [])
        if not parts:
            continue
        buf = ""
        first, prev_plain = True, False
        for seg, txt in parts:
            plain = seg["id"] in PLAIN
            if not first and not plain and not prev_plain:
                buf += sep
            if emoji_on and EMOJI.get(seg["id"]):
                txt = EMOJI[seg["id"]] + " " + txt
            url = link_url(seg, d)
            if url:
                txt = "\033]8;;%s\a%s\033]8;;\a" % (url, txt)
            code = color_seq(seg, d)
            emph = seg.get("emphCode", 1)
            buf += "\033[%d;%sm%s\033[0m" % (emph, code, txt)
            first, prev_plain = False, plain
        out.append(buf)
    sys.stdout.write("\n".join(out) + ("\n" if out else ""))

if __name__ == "__main__":
    main()
'''


def main():
    if len(sys.argv) != 3:
        print("usage: generate.py <choice.json> <output.py>", file=sys.stderr)
        sys.exit(2)
    choice = json.load(open(sys.argv[1]))
    script = TEMPLATE.replace("__CONFIGREPR__", repr(json.dumps(choice)))
    with open(sys.argv[2], "w") as f:
        f.write(script)
    print("wrote", sys.argv[2])


if __name__ == "__main__":
    main()
